### ISSUE TITLE
Problem getting started: "ck.Knot(...)" fails with 'Waiter StackCreateComplete failed'

### ISSUE THREAD

**Issue by CarlKCarlK** [nrdg/cloudknot#205] opened 2020-04-19 22:45 UTC
That for providing cloudknot.

I'm trying to run the 00 and 01 examples, but get this message.

```
~/anaconda3/lib/python3.7/site-packages/botocore/waiter.py in wait(self, **kwargs)
    321                     name=self.name,
    322                     reason='Waiter encountered a terminal failure state',
--> 323                     last_response=response,
    324                 )
    325             if num_attempts >= max_attempts:

WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state
```

I can't figure out how to figure out what is wrong. (There is nothing in the log. I set the logging level to logging.INFO.)

I'm running under an AWS administrator account that (on AWS) let me run little batch jobs.

My configuration may be new, but should work. It is Ubuntu under Windows. (Docker seems fine.). I've run Anaconda on Ubuntu under Windows routinely with other project.

Thanks for any suggestions you can provide.
- Carl

**Comment by arokem** [comment] 2020-04-19 23:01
Hi Carl,

Thanks for checking in here. I believe that this is a duplicate of #155 and
should be resolved on master. Did you install from pypi? If so, could you
please upgrade to current master and give it a try?

**Comment by CarlKCarlK** [comment] 2020-04-20 00:07
That worked. (Namely:
> pip uninstall cloudknot
> pip install git+https://github.com/richford/cloudknot.git
). Thanks! Thanks!

- Carl
p.s. Minor thing I noticed: When I ran this from example_01:
>result_futures = knot.map(range(10), env_vars=[{'name': 'MY_ENV_VAR', 'value': 'foo'}])
1. It only ran on one machine. I assume that is some AWS batch configuration I need to change.
2. Instead of returning a list of one future, it returned just one future.
I was surprised the return type (list vs singleton) seemed to depend on my AWS configuration, not my knot.map command.
[If this seems interesting to track. Let me know and I'll post it as a new issue.]

**Comment by arokem** [comment] 2020-04-22 12:59
On Sun, Apr 19, 2020 at 5:07 PM Carl Kadie <notifications@github.com> wrote:

> That worked. (Namely:
>
> pip uninstall cloudknot
> pip install git+https://github.com/richford/cloudknot.git
> ). Thanks! Thanks!
>
>
>    - Carl
>
> Awesome. I will close this issue. More below:


>
>    - p.s. Minor thing I noticed: When I ran this from example_01:
>
> result_futures = knot.map(range(10), env_vars=[{'name': 'MY_ENV_VAR',
> 'value': 'foo'}])
>
>
>    1. It only ran on one machine. I assume that is some AWS batch
>    configuration I need to change.
>
> Batch tends to pack as many jobs as it can onto one machine. You can
configure the instance type and memory requirements as key-word arguments
to ck.Knot


>
>    1. Instead of returning a list of one future, it returned just one
>    future.
>    I was surprised the return type (list vs singleton) seemed to depend
>    on my AWS configuration, not my knot.map command.
>    [If this seems interesting to track. Let me know and I'll post it as a
>    new issue.]
>
> Please do post an issue about this. I am curious what exactly you meant
here.

**Comment by arokem** [comment] 2020-04-22 13:00
Also, please note that we just moved the repo to https://github.com/nrdg/cloudknot, so do not be alarmed/confused by that.

**Closed** 2020-04-22 12:59 UTC
