### ISSUE TITLE
Cloudknot EC2 instances running out of space

### ISSUE THREAD

**Issue by ccurtis7** [nrdg/cloudknot#154] opened 2018-07-19 17:45 UTC
Despite increasing the cloudknot memory option, I continue to get the following errors when sending jobs to Cloudknot:

![image](https://user-images.githubusercontent.com/16652719/42960379-781a4176-8b40-11e8-8941-c859b2ad299c.png)

It seems to error out in the step directly after I download the image to analyze from S3. These images are fairly large (5GB), but I thought I was asking for enough memory. I had this code working before I transferred analysis to a different AWS account, so I don't know what's different now.

`knot = ck.Knot(name='download_and_track_b{}'.format(start_knot),
       docker_image = my_image,
       memory = 64000,
       resource_type = "SPOT",
       bid_percentage = 100,
       image_id = 'ami-091394c6115be83b3',
       pars_policies=('AmazonS3FullAccess',))
result_futures = knot.map(to_track)`

**Comment by arokem** [comment] 2018-07-19 17:53
The problem is not RAM on the machines you are getting, but disk space.

If you are using the default Batch AMI, that has only 30GB of disk space,
and your data might be exceeding that. I think that the solution to that is
to create a new AMI from this AMI, initialized with a much larger hard
drive.

**Comment by ccurtis7** [comment] 2018-07-19 18:16
I did that too: 1024GB HAS to be enough, right?

![image](https://user-images.githubusercontent.com/16652719/42961889-073912e8-8b45-11e8-9c51-f5783ddad265.png)

**Comment by ccurtis7** [comment] 2018-07-19 18:16
Oh wait, maybe the answer is in the image. I don't need that much space; I just need to add extra space in root, instead of EBS?

**Comment by arokem** [comment] 2018-07-19 18:19
That's right. The extra space needs to be in your root drive to be
accessible.

**Comment by ccurtis7** [comment] 2018-07-19 19:39
Hmmm, still getting the error, and I added 1024GB into the root volume type.

**Comment by ccurtis7** [comment] 2018-07-19 20:03
I just triple-checked that the function I'm running works on my own EC2 instance before submitting the function on cloudknot, and it works fine on my machine without running out of memory. And I allocated more than enough memory on the machines cloudknot is calling on. It has to be an issue with the ami, but I can't figure out what

**Comment by ccurtis7** [comment] 2018-07-26 15:45
Resolved this by using a default AWS AMI, instead of modifying one I had copied over from a different account. In theory, the other AMI should have worked too, as I hadn't modified it in any way. Cloudknot is working happily now.

**Comment by richford** [comment] 2018-09-13 00:02
@ccurtis7 I talked to a product manager at AWS about this. He recommends increasing the number of inodes in your AMI (and deleting unneeded files if you have a large number of small files). He also directed me to this [stackoverflow question/response](https://stackoverflow.com/questions/35574281/increase-the-number-of-inodes-on-aws-ebs) and suggested it might be relevant.

Did you try @arokem's suggestion as well?

**Comment by richford** [comment] 2018-10-05 20:11
@ccurtis7, any updates on this? Do you want to meet up in person at eScience to try to tackle this together? We could meet sometime next week.

**Comment by ccurtis7** [comment] 2018-10-09 15:52
Hey @richford, thanks for the thoughts. I still wasn't able to fix the issue directly, but I broke my workflow into smaller portions, and I think I'm much happier running it this way. The fix would still be useful for sure, but it's not urgent anymore.

**Comment by richford** [comment] 2018-10-09 23:54
K. I'll focus on #158, which is related. That might give me more insight into the best approach for this issue. If this one is still open once I resolve #158, I'll return to it.

**Comment by richford** [comment] 2020-09-06 00:26
I believe this should be resolved with #218. Closing this under that assumption. Please feel free to reopen if I'm mistaken.

**Closed by richford** 2020-09-06 00:26 UTC
